### ISSUE TITLE
tastopo generate geo failure

### ISSUE THREAD

**Issue by cfdbwrbq** [JonathanHolvey/tastopo#3]
Hi
tastopo generate geo:-43.643611,146.8275 --out out.pdf 
gives error:
AttributeError: 'lxml.etree._Element' object has no attribute 'ancestors'
with this libraries:
```
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile requirements.in
#
certifi==2022.5.18.1
    # via requests
charset-normalizer==2.0.12
    # via requests
cssselect2==0.6.0
    # via svglib
docopt==0.6.2
    # via tastopo
idna==3.3
    # via requests
lxml==4.8.0
    # via
    #   svglib
    #   tastopo
pillow==8.4.0
    # via
    #   reportlab
    #   tastopo
reportlab==3.6.9
    # via
    #   svglib
    #   tastopo
requests==2.27.1
    # via tastopo
svglib==1.3.0
    # via tastopo
tastopo==1.1.0.post2
    # via -r requirements.in
tinycss2==1.1.1
    # via
    #   cssselect2
    #   svglib
urllib3==1.26.9
    # via requests
webencodings==0.5.1
    # via
    #   cssselect2
    #   tinycss2
```

**Comment by JonathanHolvey** [comment]
Yes, it appears there's some conflict between newer versions of lxml and svglib that I haven't had a chance to resolve yet. As a work around, you can use the `--format SVG` option, but you'll have to convert the resulting SVG document to PDF manually.
